#!/usr/bin/env bash
# Script that configures Nginx server so that /redirect_me
# redirects to another page
sudo apt-get update -y
sudo apt-get install -y nginx
sudo echo 'Hello World' | sudo tee /var/www/html/index.html
redir="location /redirect_me {\nreturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n}\n"
sudo sed -i "30i $redir" /etc/nginx/sites-available/default
sudo service nginx restart
