#!/usr/bin/env bash
# Script that configures Nginx server so that /redirect_me
# redirects to another page
sudo apt-get update -y
sudo apt-get install -y nginx
sudo echo 'Hello World' | sudo tee /var/www/html/index.html
replace="location / {"
redir="location /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n\tlocation / {"
sudo sed -i "s|$replace|$redir|1" /etc/nginx/sites-available/default
sudo service nginx restart
