#!/usr/bin/env bash
# Script that configures server to have a custom 404 page
sudo apt-get update -y
sudo apt-get install -y nginx
sudo echo 'Hello World' | sudo tee /var/www/html/index.html
service nginx start
redir="location /redirect_me {\nreturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n}\n"
sudo sed -i "30i $redir" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /etc/nginx/html/custom_404.html
new_phrase="4-not_found_page_404 /custom_404.html;\nlocation = /custom_404.html {\nroot /usr/share/nginx/html;\ninternal;\n}\n"
sudo sed  -i "30i $new_phrase" /etc/nginx/sites-available/default
sudo service nginx restart
