#!/usr/bin/env bash
# Script that installs/configures HAproxy on lb-01 server

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy
sudo sed -i "s/ENABLED=0/ENABLED=1/" /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original
sudo sed -i "$ a\listen 4918-lb-01\n\tbind *:80\n\tmode http\n\tbalance roundrobin\n\toption httpclose\n\toption forwardfor\n\tserver 4918-web-02 54.235.18.3:80 check\n\tserver 4918-web-01 54.89.165.79:80 check" /etc/haproxy/haproxy.cfg
sudo service haproxy start
